GroupBy Merge or Join

In [2]:
import pandas as pd

In [3]:
exp=pd.read_excel("subdata_pandas/expense.xlsx")
exp.head(5)

        Date    Category Sub-Category   Amount Payment Mode
0 2023-01-01     Grocery       Grocery      30         Cash
1 2023-01-02        Food    Restaurant     890          UPI
2 2023-01-04        Food        Zomato     257          NaN
3 2023-01-06  Essentials         Diary     120          UPI
4 2023-01-06  Essentials       Perfume    1500         Cash

In [5]:
exp.groupby('Category')['Amount'].sum()#type1

Category
Bills         18724
Clothes        2890
Essentials     4485
Food           3022
Grocery        1028
Name: Amount, dtype: int64

In [6]:
exp.groupby('Category')['Amount'].agg([sum])#type2

              sum
Category
Bills       18724
Clothes      2890
Essentials   4485
Food         3022
Grocery      1028

In [ ]:
exp.groupby('Category')['Amount'].agg(['sum','count','mean','max','min'])#give a complete expense summary for each category.

              sum  count         mean    max   min
Category
Bills       18724      3  6241.333333  16000  1074
Clothes      2890      2  1445.000000   1890  1000
Essentials   4485      7   640.714286   1500    50
Food         3022      9   335.777778    890    10
Grocery      1028      8   128.500000    456    26

In [9]:
# how much money was paid using each payment mode
exp.groupby("Payment Mode")['Amount'].sum()

Payment Mode
Card      780
Cash     4637
UPI     23305
Name: Amount, dtype: int64

In [10]:
#how many transaction were made using each payment mode?
exp.groupby("Payment Mode")["Amount"].agg(['count'])

              count
Payment Mode
Card              1
Cash              8
UPI              16

In [12]:
#for each payment mode, calculate the  total amount spent across
exp.groupby(['Payment Mode','Category'])['Amount'].agg(['count'])

                         count
Payment Mode Category
Card         Food            1
Cash         Essentials      3
             Food            1
             Grocery         4
UPI          Bills           3
             Clothes         1
             Essentials      2
             Food            6
             Grocery         4

In [ ]:
#which categories have the highest total expenses?
exp.groupby(['Payment Mode','Category'])['Amount'].sum().sort_values(ascending=False)

Payment Mode  Category
UPI           Bills         18724
Cash          Essentials     3415
UPI           Clothes        1890
              Food           1455
              Essentials      900
Card          Food            780
Cash          Grocery         692
              Food            530
UPI           Grocery         336
Name: Amount, dtype: int64

In [15]:
#for each category how much amount spend using each payament mode
exp.groupby(['Category','Payment Mode'])['Amount'].sum()

Category    Payment Mode
Bills       UPI             18724
Clothes     UPI              1890
Essentials  Cash             3415
            UPI               900
Food        Card              780
            Cash              530
            UPI              1455
Grocery     Cash              692
            UPI               336
Name: Amount, dtype: int64

In [17]:
#-----------------------Task----------------

#create a DataFrame containing the total expense of each category.
#what is the average transaction amount for each payment mode?
#find the highest individual transaction in each category
#Show total,average,minimum and maximum transaction amount for each payment mode.

### Merge Or Join

In [3]:
customer=pd.read_csv("subdata_pandas/customer.csv")
customer

   customerid firstname  lastname  address
0           1      Mary     Smith    Delhi
1           3     Linda  Williams    Udupi
2           4   Barbara     Jones  Chennai
3           2     Madan     Mohan   Mumbai
4          17         R    Madhav      Goa

In [4]:
payment=pd.read_csv("subdata_pandas/payment.csv")
payment

   customerid  amount            mode paymentdate
0           1      60            Cash  2020-09-24
1          11      80            Cash  2021-03-01
2           2     500     Credit Card  2020-04-27
3           8     100            Cash  2021-01-26
4           7      20  Mobile Payment  2021-02-01
5          17     250     Credit Card  2021-04-01
6          10      70  Mobile Payment  2021-02-28

In [5]:
#inner join
pd.merge(left=customer,right=payment,on='customerid',how='inner')

   customerid firstname lastname address  amount         mode paymentdate
0           1      Mary    Smith   Delhi      60         Cash  2020-09-24
1           2     Madan    Mohan  Mumbai     500  Credit Card  2020-04-27
2          17         R   Madhav     Goa     250  Credit Card  2021-04-01

In [6]:
#left join
pd.merge(left=customer,right=payment,on='customerid',how='left')

   customerid firstname  lastname  address  amount         mode paymentdate
0           1      Mary     Smith    Delhi    60.0         Cash  2020-09-24
1           3     Linda  Williams    Udupi     NaN          NaN         NaN
2           4   Barbara     Jones  Chennai     NaN          NaN         NaN
3           2     Madan     Mohan   Mumbai   500.0  Credit Card  2020-04-27
4          17         R    Madhav      Goa   250.0  Credit Card  2021-04-01

In [8]:
#Right join
pd.merge(left=customer,right=payment,on='customerid',how='right')

   customerid firstname lastname address  amount            mode paymentdate
0           1      Mary    Smith   Delhi      60            Cash  2020-09-24
1          11       NaN      NaN     NaN      80            Cash  2021-03-01
2           2     Madan    Mohan  Mumbai     500     Credit Card  2020-04-27
3           8       NaN      NaN     NaN     100            Cash  2021-01-26
4           7       NaN      NaN     NaN      20  Mobile Payment  2021-02-01
5          17         R   Madhav     Goa     250     Credit Card  2021-04-01
6          10       NaN      NaN     NaN      70  Mobile Payment  2021-02-28

In [4]:
exp.groupby('Category')['Amount'].sum().reset_index()
exp.groupby('Payment Mode')['Amount'].mean().reset_index()
exp.groupby('Category')['Amount'].max().reset_index()
exp.groupby('Payment Mode')['Amount'].agg(['sum', 'mean', 'max']).reset_index()

  Payment Mode    sum       mean    max
0         Card    780   780.0000    780
1         Cash   4637   579.6250   1500
2          UPI  23305  1456.5625  16000

In [5]:
exp.groupby('Category')['Amount'].sum().reset_index()

     Category  Amount
0       Bills   18724
1     Clothes    2890
2  Essentials    4485
3        Food    3022
4     Grocery    1028

In [6]:
exp.groupby('Payment Mode')['Amount'].mean().reset_index()

  Payment Mode     Amount
0         Card   780.0000
1         Cash   579.6250
2          UPI  1456.5625

In [7]:
exp.groupby('Category')['Amount'].max().reset_index()

     Category  Amount
0       Bills   16000
1     Clothes    1890
2  Essentials    1500
3        Food     890
4     Grocery     456

In [8]:
exp.groupby('Category')['Amount'].max().reset_index()

     Category  Amount
0       Bills   16000
1     Clothes    1890
2  Essentials    1500
3        Food     890
4     Grocery     456

In [16]:
# 1. Total expense of each category
exp.groupby('Category')['Amount'].sum()

Category
Bills         18724
Clothes        2890
Essentials     4485
Food           3022
Grocery        1028
Name: Amount, dtype: int64

In [15]:
# 2. Average transaction amount for each payment mode
exp.groupby('Payment Mode')['Amount'].mean()

Payment Mode
Card     780.0000
Cash     579.6250
UPI     1456.5625
Name: Amount, dtype: float64

In [13]:
# 3. Highest individual transaction in each category
exp.groupby('Category')['Amount'].max()

Category
Bills         16000
Clothes        1890
Essentials     1500
Food            890
Grocery         456
Name: Amount, dtype: int64

In [17]:

exp.groupby('Payment Mode')['Amount'].agg(
    ['sum', 'mean', 'min', 'max']
)

                sum       mean  min    max
Payment Mode
Card            780   780.0000  780    780
Cash           4637   579.6250   30   1500
UPI           23305  1456.5625   10  16000