### Compare Pivoting and Melting Dataframe

In [1]:
import pandas as pd

### Compare

In [2]:
shop_stock_06Oct={
    'Fruits':['Mango','Apple','Banana','Papaya'],
    'Price':[100,150,60,30],
    'Qunt':[10,15,6,3],

}
stock_06Oct_df=pd.DataFrame(shop_stock_06Oct)
shop_stock_07Oct={
    'Fruits':['Mango','Apple','Banana','Papaya'],
        'Price':[150,200,60,35],
        'Qunt':[15,12,12,8],

}
stock_07Oct_df=pd.DataFrame(shop_stock_07Oct)

In [3]:
#-------------Compare--------------
stock_06Oct_df.compare(stock_07Oct_df)

   Price        Qunt
    self  other self other
0  100.0  150.0   10    15
1  150.0  200.0   15    12
2    NaN    NaN    6    12
3   30.0   35.0    3     8

In [4]:
stock_06Oct_df.compare(stock_07Oct_df,align_axis=0)

         Price  Qunt
0 self   100.0    10
  other  150.0    15
1 self   150.0    15
  other  200.0    12
2 self     NaN     6
  other    NaN    12
3 self    30.0     3
  other   35.0     8

In [11]:
#-------------compare-----------
#self                       #others
stock_06Oct_df.compare(stock_07Oct_df)
stock_06Oct_df.compare(stock_07Oct_df,align_axis=0)
stock_06Oct_df.compare(stock_07Oct_df,keep_equal=True)
stock_06Oct_df.compare(stock_07Oct_df,keep_shape=True)
stock_06Oct_df.compare(stock_07Oct_df,align_axis=0,keep_equal=True,keep_shape=True)

         Fruits  Price  Qunt
0 self    Mango    100    10
  other   Mango    150    15
1 self    Apple    150    15
  other   Apple    200    12
2 self   Banana     60     6
  other  Banana     60    12
3 self   Papaya     30     3
  other  Papaya     35     8

In [6]:
stock_06Oct_df.compare(stock_07Oct_df,keep_equal=True)

  Price       Qunt
   self other self other
0   100   150   10    15
1   150   200   15    12
2    60    60    6    12
3    30    35    3     8

In [7]:
stock_06Oct_df.compare(stock_07Oct_df,keep_shape=True)

  Fruits        Price        Qunt
    self other   self  other self other
0    NaN   NaN  100.0  150.0   10    15
1    NaN   NaN  150.0  200.0   15    12
2    NaN   NaN    NaN    NaN    6    12
3    NaN   NaN   30.0   35.0    3     8

In [8]:
stock_06Oct_df.compare(stock_07Oct_df,align_axis=0,keep_equal=True,keep_shape=True)

         Fruits  Price  Qunt
0 self    Mango    100    10
  other   Mango    150    15
1 self    Apple    150    15
  other   Apple    200    12
2 self   Banana     60     6
  other  Banana     60    12
3 self   Papaya     30     3
  other  Papaya     35     8

In [10]:
# Pivoting

shop_sales={
    'Product':['laptop','mobile','laptop','mobile','laptop','mobile','laptop'],
    'Month':['jan','jan','feb','feb','mar','mar','apr'],
    'Price':[50000,12000,65000,25000,70000,35000,70000],
}
sales_df=pd.DataFrame(shop_sales)
sales_df

  Product Month  Price
0  laptop   jan  50000
1  mobile   jan  12000
2  laptop   feb  65000
3  mobile   feb  25000
4  laptop   mar  70000
5  mobile   mar  35000
6  laptop   apr  70000

In [12]:
#------------Pivot----------
sales_df.pivot(
    index="Product",
    columns="Month",
    values="Price"

)

Month        apr      feb      jan      mar
Product
laptop   70000.0  65000.0  50000.0  70000.0
mobile       NaN  25000.0  12000.0  35000.0

In [19]:
# Pivoting

shop_sales={
    'Product':['laptop','mobile','laptop','mobile','laptop','mobile','laptop'],
    'Month':['jan','jan','feb','feb','mar','mar','mar'],
    'Price':[50000,12000,65000,25000,70000,35000,70000],
}
sales_df=pd.DataFrame(shop_sales)
sales_df

  Product Month  Price
0  laptop   jan  50000
1  mobile   jan  12000
2  laptop   feb  65000
3  mobile   feb  25000
4  laptop   mar  70000
5  mobile   mar  35000
6  laptop   mar  70000

In [25]:
#------------Pivot----------
sales_df.pivot_table(
    index="Product",
    columns="Month",
    values="Price",
    aggfunc="sum"

)

Month      feb    jan     mar
Product
laptop   65000  50000  140000
mobile   25000  12000   35000

### Melting

In [27]:
sales_data={
    "product":['laptop','mobile','camera'],
    "jan":[145000,50000,265000],
    "feb":[245000,10000,365000],
    "mar":[345000,11000,465000]
}
sales_df=pd.DataFrame(sales_data)

In [28]:
sales_df.melt(
    id_vars="product",
    var_name="month",
    value_name="sales"
)

  product month   sales
0  laptop   jan  145000
1  mobile   jan   50000
2  camera   jan  265000
3  laptop   feb  245000
4  mobile   feb   10000
5  camera   feb  365000
6  laptop   mar  345000
7  mobile   mar   11000
8  camera   mar  465000