## Dealing with Duplicates values, Missing Data

In [1]:
import pandas as pd

### Duplicates

In [2]:
cdata=pd.read_csv("subdata_pandas/company.csv")
cdata

    EEID      Name gender   salary
0  EMP01    ayushi      F      NaN
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali    NaN  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05       NaN      M  25000.0
5  EMP06     rohit      M      NaN
6  EMP02     rohit      M  25000.0

In [ ]:
#check Boolean format
cdata.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [ ]:
#select duplicate row
cdata[cdata.duplicated()]

    EEID   Name gender   salary
6  EMP02  rohit      M  25000.0

In [9]:
cdata["EEID"].duplicated() #Boolean

0    False
1    False
2    False
3     True
4    False
5    False
6     True
Name: EEID, dtype: bool

In [8]:

cdata[cdata["EEID"].duplicated()]

    EEID    Name gender   salary
3  EMP01  ayushi      F  20000.0
6  EMP02   rohit      M  25000.0

In [10]:
cdata["Name"].duplicated()

0    False
1    False
2    False
3     True
4    False
5     True
6     True
Name: Name, dtype: bool

In [11]:
cdata[cdata["Name"].duplicated()]

    EEID    Name gender   salary
3  EMP01  ayushi      F  20000.0
5  EMP06   rohit      M      NaN
6  EMP02   rohit      M  25000.0

In [14]:
#Drop duplicate
cdata.drop_duplicates()

    EEID      Name gender   salary
0  EMP01    ayushi      F      NaN
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali    NaN  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05       NaN      M  25000.0
5  EMP06     rohit      M      NaN

In [15]:
cdata["EEID"].drop_duplicates()

0    EMP01
1    EMP02
2    EMP03
4    EMP05
5    EMP06
Name: EEID, dtype: str

### Missing data

In [17]:
cdata=pd.read_csv("subdata_pandas/company.csv")
cdata

    EEID      Name gender   salary
0  EMP01    ayushi      F      NaN
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali    NaN  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05       NaN      M  25000.0
5  EMP06     rohit      M      NaN
6  EMP02     rohit      M  25000.0

In [18]:
cdata.isnull()

    EEID   Name  gender  salary
0  False  False   False    True
1  False  False   False   False
2  False  False    True   False
3  False  False   False   False
4  False   True   False   False
5  False  False   False    True
6  False  False   False   False

In [19]:
cdata.isnull().sum()

EEID      0
Name      1
gender    1
salary    2
dtype: int64

In [20]:
#Elemenate null rows
cdata.dropna()

    EEID    Name gender   salary
1  EMP02   rohit      M  25000.0
3  EMP01  ayushi      F  20000.0
6  EMP02   rohit      M  25000.0

In [21]:
import numpy as np

In [ ]:
cdata.replace(np.nan,"Empty_data") # Replace -->overall

    EEID        Name      gender      salary
0  EMP01      ayushi           F  Empty_data
1  EMP02       rohit           M     25000.0
2  EMP03    pranjali  Empty_data     27000.0
3  EMP01      ayushi           F     20000.0
4  EMP05  Empty_data           M     25000.0
5  EMP06       rohit           M  Empty_data
6  EMP02       rohit           M     25000.0