Column Transformation in pandas

In [2]:
import pandas as pd

Rows and col selection

In [5]:
sdata=pd.read_csv("subdata-pandas/student.csv")
sdata

    id firstName  lastName  age  marks   fees
0  101    Akshay    Shetty   20     85  25000
1  102    Ananya       Rao   21     92  30000
2  103     Rohit  Bhandary   19     76  28000
3  104     Nisha   D'Souza   20     88  25000
4  105   Karthik   Poojary   22     69  32000
5  106    Shreya    Shetty   19     95  30000
6  107     Rohan      Naik   21     72  27000
7  108   Deepika      Bhat   20     81  28000
8  109  Abhishek    Kotian   22     64  26000
9  110     Pooja       Rai   19     90  30000

In [7]:
#select column from table
sdata[['firstName','marks','fees']]

  firstName  marks   fees
0    Akshay     85  25000
1    Ananya     92  30000
2     Rohit     76  28000
3     Nisha     88  25000
4   Karthik     69  32000
5    Shreya     95  30000
6     Rohan     72  27000
7   Deepika     81  28000
8  Abhishek     64  26000
9     Pooja     90  30000

In [ ]:
#select rows based on condition
sdata.loc[sdata.id==106]
sdata.loc[sdata.firstName=="Pooja"]
sdata.loc[sdata.age>20]

    id firstName lastName  age  marks   fees
1  102    Ananya      Rao   21     92  30000
4  105   Karthik  Poojary   22     69  32000
6  107     Rohan     Naik   21     72  27000
8  109  Abhishek   Kotian   22     64  26000

In [14]:
#slicing-rows loc[strt index:endidex]
sdata.loc[2:6]
#slicing on-rows and col iloc[strtIdx: endIdx-1,startIdx:endIdx-1]
sdata.iloc[1:5,1:4]

  firstName  lastName  age
1    Ananya       Rao   21
2     Rohit  Bhandary   19
3     Nisha   D'Souza   20
4   Karthik   Poojary   22

Filter

In [ ]:
sdata=pd.read_csv("subdata-pandas/student.csv")
sdata

In [19]:
sdata['age']>20 #boolean
sdata[sdata['age']>20]
sdata_age_filter=sdata[sdata['age']>20]
sdata_age_filter

    id firstName lastName  age  marks   fees
1  102    Ananya      Rao   21     92  30000
4  105   Karthik  Poojary   22     69  32000
6  107     Rohan     Naik   21     72  27000
8  109  Abhishek   Kotian   22     64  26000

In [24]:
sdata.where(sdata['age']>20,other="not eligible")
sdata.where(sdata['marks']>=85,other="not selected")

,id,firstName,lastName,age,marks,fees
0,101,Akshay,Shetty,20,85,25000
1,102,Ananya,Rao,21,92,30000
2,not selected,not selected,not selected,not selected,not selected,not selected
3,104,Nisha,D'Souza,20,88,25000
4,not selected,not selected,not selected,not selected,not selected,not selected
5,106,Shreya,Shetty,19,95,30000
6,not selected,not selected,not selected,not selected,not selected,not selected
7,not selected,not selected,not selected,not selected,not selected,not selected
8,not selected,not selected,not selected,not selected,not selected,not selected
9,110,Pooja,Rai,19,90,30000

In [26]:
sdata.loc[sdata['marks']>=85, "Result"]="selected"
sdata.loc[sdata['marks']<85, "Result"]="Not selected"
sdata

    id firstName  lastName  age  marks   fees        Result
0  101    Akshay    Shetty   20     85  25000      selected
1  102    Ananya       Rao   21     92  30000      selected
2  103     Rohit  Bhandary   19     76  28000  Not selected
3  104     Nisha   D'Souza   20     88  25000      selected
4  105   Karthik   Poojary   22     69  32000  Not selected
5  106    Shreya    Shetty   19     95  30000      selected
6  107     Rohan      Naik   21     72  27000  Not selected
7  108   Deepika      Bhat   20     81  28000  Not selected
8  109  Abhishek    Kotian   22     64  26000  Not selected
9  110     Pooja       Rai   19     90  30000      selected

In [27]:
sdata=pd.read_csv("subdata-pandas/student.csv")
sdata
sdata['FullName']=sdata['firstName']+" "+sdata['lastName']
sdata

    id firstName  lastName  age  marks   fees         FullName
0  101    Akshay    Shetty   20     85  25000    Akshay Shetty
1  102    Ananya       Rao   21     92  30000       Ananya Rao
2  103     Rohit  Bhandary   19     76  28000   Rohit Bhandary
3  104     Nisha   D'Souza   20     88  25000    Nisha D'Souza
4  105   Karthik   Poojary   22     69  32000  Karthik Poojary
5  106    Shreya    Shetty   19     95  30000    Shreya Shetty
6  107     Rohan      Naik   21     72  27000       Rohan Naik
7  108   Deepika      Bhat   20     81  28000     Deepika Bhat
8  109  Abhishek    Kotian   22     64  26000  Abhishek Kotian
9  110     Pooja       Rai   19     90  30000        Pooja Rai

In [29]:
sdata=pd.read_csv("subdata-pandas/student.csv")
sdata
sdata['after discount of 10%']=sdata['fees']-(sdata['fees']*10)/100
sdata

    id firstName  lastName  age  marks   fees  after discount of 10%
0  101    Akshay    Shetty   20     85  25000                22500.0
1  102    Ananya       Rao   21     92  30000                27000.0
2  103     Rohit  Bhandary   19     76  28000                25200.0
3  104     Nisha   D'Souza   20     88  25000                22500.0
4  105   Karthik   Poojary   22     69  32000                28800.0
5  106    Shreya    Shetty   19     95  30000                27000.0
6  107     Rohan      Naik   21     72  27000                24300.0
7  108   Deepika      Bhat   20     81  28000                25200.0
8  109  Abhishek    Kotian   22     64  26000                23400.0
9  110     Pooja       Rai   19     90  30000                27000.0